name: Auto Assign Reviewers
on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          numberOfReviewers: 2
          addReviewers: true          # Default
          addAssignees: false         # Don't assign people, just request reviews
          reviewers: |
            JMac1066
            wimvelzeboer