name: PR Slack Notification

on:
  pull_request:
    types: [opened]

env:
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Slack
        run: |
          curl -X POST -H 'Content-type: application/json' -H 'Authorization: Bearer ${{ secrets.SLACK_TOKEN}}' --data "{\"channel\":\"gitbook-pr-test\",\"text\":\"New PR created\\nDetails: *${{github.event.pull_request.title}}*\\nAuthor: *${{github.event.pull_request.user.login}}*\\n${{github.event.pull_request.html_url}}\"}" https://slack.com/api/chat.postMessage	
