name: Test Workflow
on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Simple test
        run: echo "Workflow is running!"

      - name: Test Slack webhook
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Test message from GitHub Actions"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}